site_name: Matt's thoughts on things

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/book.png
  features:
    - navigation.footer

plugins:
  - search # necessary for search to work
  - git-revision-date-localized
  - social
  - blog:
      post_date_format: full


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/matthewburke1995
    - icon: fontawesome/brands/github
      link: https://github.com/MatthewBurke1995

site_url: https://matthewburke.xyz

nav:
  - Blog:
    - blog/index.md 
  - Projects:
    - projects/index.md
    - projects/posts/wondrous.md
