name: Update Blog CI

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2.1
      with:
        switches: -avzr --delete
        path: site/
        remote_path: /home/project/data/static/blog
        remote_host: matthewburke.xyz
        remote_user: matt
        remote_key: ${{ secrets.PRIVATE_RSA }}
